<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
     
    <link rel="stylesheet" href=" module-2.css/styles.css">
  </head>
<meta name="viewport" content="width=device-width, initial-scale=1">

<title>COURSERA PEER GRADED </title>
<style>

/********** Base styles **********/
* {
  box-sizing: border-box;
}

divclass {
margin-top: 20px;
align:right;
}
h1 {
  margin-bottom: 15px;
  align:center;
}

p {
  border: 1px solid black;
  background-color: #A52A2A;
  width: 90%;
  height: 150px;
  margin-right: auto;
  margin-left: auto;
  font-family: Helvetica;
  color: white;
}
body{
font-family: Arial;
Color: red;
Align:center;
}

.row {
  width: 100%;
}

/********** Large devices only **********/
@media (min-width: 1200px) {
  .col-lg-1, .col-lg-2, .col-lg-3, {
    float: left;
    border: 2px solid green;
  }
  .col-lg-1 {
    width: 33.33%;
  }
  .col-lg-2 {
    width: 33.33%;
  }
  .col-lg-3 {
    width: 33%;
  }
  
}

/********** Medium devices only **********/
@media (min-width: 992px) and (max-width: 1199px) {
  .col-md-1, .col-md-2, .col-md-3, {
    float: left;
    border: 2px solid green;
  }
  .col-md-1 {
    width: 33.33%;
  }
  .col-md-2 {
    width: 33.33%;
  }
  .col-md-3 {
    width: 33%;
  
}

</style>
</head>

<h1>GLOBAL MENUS</h1>

<div class="row">
  <div class="col-lg-3 col-md-6"><p>MENU CHICKEN</p></div>

<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu.</p>

<div id="Chickencont">

</div>
</div>

<div id="Beef">
<p>https://itunes.apple.com/us/album/preludes-etude-n-12-alexander-scriabin-op-74-op-67-op-17-op-8/id1230769143</p>
<div id="Beefcont">

</div>



<div id="Sushi">
<p>https://itunes.apple.com/us/album/preludes-etude-n-12-alexander-scriabin-op-74-op-67-op-17-op-8/id1230769143</p>
<div id="Sushicont">

</div>

	

</body>
</html>


  
</div>


</body>
</html>
